version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
  - source: /scripts
    destination: /opt/scripts
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh  # Optional: Add if needed to stop services or clean up
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
